backend:
  name: github
  repo: iRON5/nextjs-netlify
  branch: stage
  base_url: https://romco.site
  auth_endpoint: api/auth
  open_authoring: true
media_folder: /public/img
public_folder: img
publish_mode: editorial_workflow
# i18n:
#   # Required and can be one of multiple_folders, multiple_files or single_file
#   # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
#   # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
#   # single_file - persists a single file in `<folder>/<slug>.<extension>`
#   structure: multiple_files

#   # Required - a list of locales to show in the editor UI
#   locales: [en, ru]

#   # Optional, defaults to the first item in locales.
#   # The locale to be used for fields validation and as a baseline for the entry.
#   default_locale: en
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home (en)'
        name: 'home_en'
        filter:
          field: language
          value: en
        file: 'content/home/en.md'
        preview_path: /api/preview?slug=home&ln=en
        fields:
          - {
              label: Language,
              name: language,
              widget: select,
              options: [en, ru],
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Home (ru)'
        name: 'home_ru'
        filter:
          field: language
          value: ru
        file: 'content/home/en.md'
        preview_path: /api/preview?slug=home&ln=ru
        fields:
          - { label: Язык, name: language, widget: select, options: [en, ru] }
          - { label: 'Заголовок', name: 'title', widget: 'string' }
          - { label: 'Дата Публикации', name: 'date', widget: 'datetime' }
          - { label: 'Текст', name: 'body', widget: 'markdown' }
      - label: 'About (en)'
        name: 'about_en'
        file: 'content/about/en.md'
        preview_path: /api/preview?slug=about&ln=en
        filter:
          field: language
          value: en
        fields:
          - {
              label: Language,
              name: language,
              widget: select,
              options: [en, ru],
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About (ru)'
        name: 'about_ru'
        file: 'content/about/ru.md'
        preview_path: /api/preview?slug=about&ln=ru
        filter:
          field: language
          value: ru
        fields:
          - { label: Язык, name: language, widget: select, options: [en, ru] }
          - { label: 'Заголовок', name: 'title', widget: 'string' }
          - { label: 'Дата Публикации', name: 'date', widget: 'datetime' }
          - { label: 'Текст', name: 'body', widget: 'markdown' }
  - label: 'Blog posts (en)'
    name: 'blog_en'
    # same as the top level, but all fields are optional and defaults to the top level
    # can also be a boolean to accept the top level defaults
    # i18n: true
    folder: 'content/posts/en'
    slug: '{{fields.slug}}'
    preview_path: /api/preview?slug=blog/{{fields.slug}}&ln=en
    filter:
      field: language
      value: en
    create: true
    fields:
      - { label: Language, name: language, widget: select, options: [en, ru] }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'URL Slug', name: 'slug', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Blog posts (ru)'
    name: 'blog_ru'
    folder: 'content/posts/ru'
    slug: '{{fields.slug}}'
    preview_path: /api/preview?slug=blog/{{fields.slug}}&ln=ru
    filter:
      field: language
      value: en
    create: true
    fields:
      - { label: Язык, name: language, widget: select, options: [en, ru] }
      - { label: 'Заголовок', name: 'title', widget: 'string', required: true }
      - {
          label: 'URL заголовок',
          name: 'slug',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Дата Публикации',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Изображение',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Текст', name: 'body', widget: 'markdown', required: true }
