backend:
  name: github
  repo: iRON5/nextjs-netlify
  branch: stage
  base_url: https://romco.site
  auth_endpoint: api/auth
  open_authoring: true
media_folder: /public/img
public_folder: img
publish_mode: editorial_workflow
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, ru]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: ru
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  - label: Home
    name: home
    i18n: true
    filter:
      field: language
      value: en
    folder: content/home
    preview_path: /api/preview?slug=home&ln={{fields.language}}
    fields:
      - { label: Language, name: language, widget: select, options: [en, ru] }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          i18n: duplicate,
          name: 'date',
          widget: 'datetime',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: About
    name: about
    i18n: true
    folder: content/home
    preview_path: /api/preview?slug=about&ln={{fields.language}}
    filter:
      field: language
      value: ru
    fields:
      - { label: Language, name: language, widget: select, options: [en, ru] }
      - { label: Title, name: title, widget: string }
      - {
          label: Publication Date,
          i18n: duplicate,
          name: date,
          widget: datetime,
        }
      - { label: Body, name: body, widget: markdown }
  - label: Blog posts
    name: blog
    folder: content/posts
    slug: '{{fields.slug}}'
    preview_path: /api/preview?slug=blog/{{fields.slug}}&ln=en
    filter:
      field: language
      value: en
    create: true
    fields:
      - { label: Language, name: language, widget: select, options: [en, ru] }
      - { label: Title, name: title, widget: string, required: true }
      - {
          label: URL Slug,
          i18n: duplicate,
          name: slug,
          widget: string,
          required: true,
        }
      - {
          label: Publish Date,
          i18n: duplicate,
          name: date,
          widget: datetime,
          required: true,
        }
      - {
          label: Featured Image,
          name: thumbnail,
          widget: image,
          required: true,
        }
      - { label: Body, name: body, widget: markdown, required: true }
